name: CI

permissions:
  contents: read
  packages: write
  checks: write
  id-token: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 🛠 Build & deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Generate envs
        id: generate_envs
        run: |-
          short_sha=$(echo '${{ github.sha }}' | cut -c1-7)
          branch_type=$(if [[ '${{ github.ref }}' == 'refs/heads/main' ]]; then echo 'main'; else echo 'feature'; fi)

          echo "short_sha=${short_sha}" >> $GITHUB_ENV
          echo "branch_type=${branch_type}" >> $GITHUB_ENV

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: 🛠 Build
        run: ./gradlew build

      - name: 📎 Publish test report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: >-
            ghcr.io/${{ github.repository }}:${{ env.branch_type }}-${{ env.short_sha }}
          platforms: linux/amd64,linux/arm64
